from typing import TypeVar, overload

from .service import Service
from .status import ManagerStatus

_ServiceT = TypeVar("_ServiceT", bound=Service)

class Launart:
    status: ManagerStatus

    def __init__(self) -> None: ...
    @classmethod
    def current(cls) -> Launart: ...
    def add_component(self, component: Service) -> None: ...
    @overload
    def get_component(self, target: type[_ServiceT]) -> _ServiceT: ...
    @overload
    def get_component(self, target: str) -> Service: ...
    def remove_component(self, component: str | Service) -> object: ...
    async def launch(self) -> None: ...
